baseurl = "/"                   # The base URL of your Hugo site
title = "42n cooki"             # The title of your Hugo site
author = "the cooki mnstr"      # The author name
googleAnalytics = ""            # Your Google Analytics tracking ID
enableRobotsTXT = true
defaultContentLanguage = "en"
language = "en-US"
paginate = 7                    # The numbers of posts per page
theme = "piercer"               # Your Hugo theme


description = "42n cooki"       # Description for the meta description tag

[params.palette]
    text = "#efefef"
    background = "#FEFAE0"
    accent = "#2a1a1f"
    foreground = "#3d3d3d"
    separator = "#c6ac8f"
    cyan = "#8be9fd"
    green = "#806443"
    orange = "#ffb86c"
    pink = "#ff79c6"
    purple = "#bd93f9"
    red = "#ff5555"
    yellow = "#f1fa8c"

[params.header]
    show = false 

[params.googlefonts]
    font = "Nanum Brush Script"   # Name of the Google Font you want to use


    